### ISSUE TITLE
IndexError: list index out of range for m.solve()

### ISSUE THREAD

**Issue by jbluebbert** [sassoftware/sasoptpy#1]
I am running the following using Viya 3.4, Python 3.6.5, and sasoptpy v0.2.0. Is this error expected? If so, how do I fix?
```
import swat
import sasoptpy as so
s = swat.CAS()
m = so.Model(name = 'lp_basic', session = s)
x = m.add_variable(lb = 100, ub = 200, name = 'x')
y = m.add_variable(lb = 80, ub = 170, name = 'y')
m.set_objective(-2*x + 5*y, sense = so.MAX, name = 'obj')
m.add_constraint(x + y >= 200, name = 'c1')
m.solve()
```

**Comment by jbluebbert** [comment]
I realized my issue was because I was using swat 1.3.0. Upgrading to swat 1.5.0 fixed the problem.

**Comment by sertalpbilal** [comment]
Thanks for bringing this up. I will add swat >= 1.4.0 requirement to the setup file.
