### ISSUE TITLE
Update to support SWAT 1.9.2?

### ISSUE THREAD

**Issue by dtherrick** [sassoftware/sasoptpy#10]
I'd like to use sasoptpy in a project, but I'm already using python-swat version 1.9.2. 

Can this package be updated to support the most recent version of swat?

**Comment by sertalpbilal** [comment]
Yes, currently working on it and it will be released soon. For now, you can install swat first and try installing sasoptpy by skipping dependencies.

**Comment by sertalpbilal** [comment]
Hi @dtherrick, I have pushed version 1.0.5 to PyPI, and it should work fine with the latest version of swat. Can you try installing/upgrading sasoptpy and let me know if it works?

**Comment by dtherrick** [comment]
@sertalpbilal - apologies! I somehow just saw this. Installed sasoptpy 1.05 from PyPi and it's all good now. Thanks for updating and I appreciate it!
