### ISSUE TITLE
Update saspy to 4.1.0

### ISSUE THREAD

**Issue by Criptic** [sassoftware/sasoptpy#11]
I just updated my saspy version from 3.3.7 to 4.1.0 and get the following error message from pip:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sasoptpy 1.0.4 requires saspy==3.3.7, but you have saspy 4.1.0 which is incompatible.

I haven't tested if sasoptpy is still working, but this error message is concerning to me.

Is there any issue here?

**Comment by Criptic** [comment]
It suggest to change it from saspy==3.3.7 to saspy >=3.3.7

**Comment by tomweber-sas** [comment]
Seems like the versions are out of synch between the repo (says 1.0.0 is the latest) and PyPi, 1.0.4 is the latest. The Pypi 1.0.4 that is on Pypi still forces a 2 year old version of saspy to be used, which is really bad. It should not care the version, or at least have >= requirement. This is causing problems for people trying to use this. In this repo, the setup.py has been change 6 or 7 months ago to remove these hard coded version requirements, but this isn't reflected in what's on PyPi. 

I think getting the versions to match between the repos and removing the single, old, version requirements on dependents need to be done else this will become more problematic.

I can't reopen this myself, but think it should be, and should be addressed.

Thanks,
Tom

**Comment by sertalpbilal** [comment]
I'm working on fixing this @Criptic, you can try reinstalling sasoptpy with skipped dependencies meanwhile.

**Comment by sertalpbilal** [comment]
I have pushed v1.0.5 to PyPI and it should work without any issues now. I have removed the version dependencies, as everything works fine with the latest versions.
https://pypi.org/project/sasoptpy/1.0.5/

**Comment by tomweber-sas** [comment]
Awesome, thanks Sertalp! I can't close this, but it can be now.

**Comment by Criptic** [comment]
Looks good, just upgraded the package the error messages are gone. Thank you!
