### ISSUE TITLE
Can we expect that constraint programming will be added in near future?

### ISSUE THREAD

**Issue by Kimiko2019** [sassoftware/sasoptpy#3]
Like LSO solver is added at V0.2.1, can we expect that CLP solver will be added in near future? CLP procedure has two kinds of formulation like “a standard CSP”, and “a scheduling CSP”. My question is for “a standard CSP” type, because “a standard CSP” can be modelled on OPTMODEL like LSO

**Comment by sertalpbilal** [comment]
I am actively working on _sasoptpy_ nowadays to match OPTMODEL functionality. The upcoming release will bring major changes, and the CLP solver is very likely to be included. It is hard to give a date at this point, but it should be available within a few months.

If you are interested, I can let you know when the development branch has the CLP added.

**Comment by Kimiko2019** [comment]
Yes, please.  We are really happy to know that.
