### ISSUE TITLE
How to get the original constraint name when we set "limit_names=True"?

### ISSUE THREAD

**Issue by Kimiko2019** [sassoftware/sasoptpy#6]
Based on your previous advice, I installed new version and we understand we have no more "-" problem. Now we would like to ask you about the constraint name for the infeasibility analysis.

###  Usual case of infeasibility  analysis
When we have a model such as;

```
import pandas as pd
import saspy
s = saspy.SASsession(cfgname='winlocal')

import sasoptpy as so
model = so.Model(name="Test Model", session=s)

x_data = pd.DataFrame([['x1',2],['x2',3],['x3',4]],columns=['name','value']).set_index(['name'])
XS=x_data.index.tolist()
value=x_data['value']
x=model.add_variables(XS, vartype=so.CONT, lb=0, name='x')
model.add_constraints((x[i] <= 5*value[i] for i in XS ),name='c010')
model.add_constraints((x[i] >= 20 for i in XS ),name='c020')

Total = so.quick_sum ( value[i]*x[i] for i in XS )
model.set_objective(Total, sense=so.MAX, name='TotalValue')

optmodeldata = model.to_optmodel()
print(optmodeldata)

status=model.solve(limit_names=True)
print(status)
```

We can understand we must check c020 constraint from the log

**NOTE: Constraint _c020_x1_ causes the problem to be infeasible.**

### With version 1.0.0.a2

When we run the long mathematical programming model, we got an error message like; 
**RuntimeError: Some object names are truncated, try submitting with limit_names=True parameter.**
To put here, it is long, so alternatively we can reproduce the same error message with changing the data like
`x_data = pd.DataFrame([['x-------------------------------1',2],['x-2',3],['x-3',4]],columns=['name','value']).set_index(['name'])`
So we change solver call like 
`status=model.solve(limit_names=True)`
Then we got following lines;
**NOTE: Constraint _o136_ causes the problem to be infeasible.
NOTE: The LP presolver found this problem to be infeasible.
NOTE: Infeasible.
NOTE: The IIS= option can be used to help diagnose the cause of infeasibility.**

We do not understand which is _o136_, so, we  called IIS;

`status=model.solve(limit_names=True,options={'with':'lp', 'IIS':True}) `
then we got;
**NOTE: The IIS= option is enabled.
(skip)
NOTE: The deletion filter removed 2 constraints and 0 variable bounds.
NOTE: The IIS= option found this problem to be infeasible.
NOTE: The IIS= option found an irreducible infeasible set with 0 variables and 2 constraints.
NOTE: The IIS solve time is 0.00 seconds.**

How can we reach the infeasible place like variable name and/or constraint name? 

### expand / IIS
If we can call expand /IIS like optmodel, let us know. If we can get this kind of output, we can use it. We do not care which is usable.
Follow is the optmodel code and it's output.
```
proc optmodel;
   var x {{'x-------------------------------1','x-2','x-3'}} >= 0;
   con c010_x_______________________________1 : x['x-------------------------------1'] <= 10;
   con c010_x_2 : x['x-2'] <= 15;
   con c010_x_3 : x['x-3'] <= 20;
   con c020_x_______________________________1 : x['x-------------------------------1'] >= 20;
   con c020_x_2 : x['x-2'] >= 20;
   con c020_x_3 : x['x-3'] >= 20;
   max TotalValue = 2 * (x['x-------------------------------1']) + 3 * (x['x-2']) + 4 * (x['x-3']);
   solve with lp / IIS = TRUE;
	expand / IIS;
quit;
```
Output is;
```
Constraint c010_x_2: x['x-2'] <= 15   
Constraint c020_x_2: x['x-2'] >= 20
```

**Comment by sertalpbilal** [comment]
Hi Kimiko,

When replaced, the long object names are stored inside an object of type `SASMediator` 
[[Source code]](https://github.com/sassoftware/sasoptpy/blob/v1.0.0-alpha/sasoptpy/interface/solver/sas_mediator.py#L11) [[API Reference]](https://sassoftware.github.io/sasoptpy/api/interface.html#sas)

Indeed, when you call `model.solve`, it directs and calls `SASMediator.solve` method. So, what you can do is make this process by hand, as follows:

``` python
from sasoptpy.interface import SASMediator
sm = SASMediator(model, s)
sm.solve(limit_names=True,options={'with':'lp', 'IIS':True})
sm.conversion
```

This should give you an output of following form:

``` shell
{'o50': 'c010_x_______________________________1',
 'o51': 'c020_x_______________________________1'}
```

For the second part of the question, you can add literal optmodel code inside sasoptpy models now. Here is the full example for you:

``` python
from sasoptpy.abstract import LiteralStatement as ls

model = so.Model(name="Test Model", session=s)

x_data = pd.DataFrame([['x-------------------------------1',2],['x-2',3],['x-3',4]],columns=['name','value']).set_index(['name'])
XS=x_data.index.tolist()
value=x_data['value']
x=model.add_variables(XS, vartype=so.CONT, lb=0, name='x')
model.add_constraints((x[i] <= 5*value[i] for i in XS ),name='c010')
model.add_constraints((x[i] >= 20 for i in XS ),name='c020')

Total = so.quick_sum ( value[i]*x[i] for i in XS )
model.set_objective(Total, sense=so.MAX, name='TotalValue')

model.add_statement(ls("ods output expand=iis_output;"))
model.add_postsolve_statement(ls("expand / IIS;"))
model.add_postsolve_statement(ls("create data con_status from [j] = {1.._NCON_} con=_CON_.name value=_CON_.body status=_CON_.status;"))

sm = SASMediator(model, s)
sm.solve(limit_names=True,options={'with':'lp', 'IIS':True}, verbose=True)
sm.conversion
```

You can use `model.add_statement` and `model.add_postsolve_statement` together with `sasoptpy.abstract.LiteralStatement`. The first statement forwards "expand" output to a table called `iis_output`. The third one is a `create data` statement for printing the IIS status (an alternative way). After you submit, you can grab tables as follows:

```python
s.sd2df('IIS_OUTPUT')
```

![image](https://user-images.githubusercontent.com/4002221/79354221-1e1f7500-7f0a-11ea-969e-f8b6269af284.png)

and

``` python
s.sd2df('CON_STATUS')
```

![image](https://user-images.githubusercontent.com/4002221/79354263-2aa3cd80-7f0a-11ea-8e75-d000d39bc93a.png)

**Comment by sertalpbilal** [comment]
See the [Jupyter notebook](https://github.com/sassoftware/sasoptpy/blob/4185cc32f0d3d301cc552ceabfdf4e1d2efb54fa/examples/issues/Issue_6.ipynb) I have added.

**Comment by Kimiko2019** [comment]
Dear Sertalp,
Thank you for your samples. Please close this question.
P.S. 
For the optimality check, I wanted to take out the "Bound Infeasibility" when we have a "Conditionally optimal solution(CONDITIONAL_OPTIMAL)". I understand that I can take it out from "SOL_SUMMARY". Thank you very much.
Regards,
Kimiko

```
from sasoptpy.abstract import LiteralStatement as ls
model = so.Model(name="Test Model", session=s)
x_data = pd.DataFrame([['x-1',2],['x-2',3],['x-3',4]],columns=['name','value']).set_index(['name'])
XS=x_data.index.tolist()
value=x_data['value']
x=model.add_variables(XS, vartype=so.INT, lb=1.00001, ub=30, name='x')
model.add_constraints((x[i] <= 5.1*value[i] for i in XS ),name='c010')
Total = so.quick_sum ( value[i]*x[i] for i in XS )
model.set_objective(Total, sense=so.MAX, name='TotalValue')
sm = SASMediator(model, s)
sm.solve(limit_names=True,options={'with':'milp'}, verbose=True)
sm.conversion
for i in s.list_tables('WORK'):
    print (i[0])
    if (i[0] == 'SOL_SUMMARY'):
        print (s.sd2df(i[0]))
```
